### PR TITLE
fix: correct typo

### PR DESCRIPTION
**Pull request by wincent**
Added nearly 8 years ago in 8f1d9b07c12c6b67706fb3bc2628a65f6b730e63.

### CODE REVIEW

**Comment by lann** [comment]
> Reviewed-by: Lann Martin <lann@causes.com>

I still approve.

**Review by lencioni — APPROVED** [review]

**Review by trotzig — APPROVED** [review]

**Comment by sds** [comment]
Anyone still have the credentials to the [`causes`](https://rubygems.org/profiles/causes) RubyGems user? 😅 

(not strictly required for this change 😃 )

**Comment by MatthewHerbst** [comment]
Hmm, @sds Miller might, I'll ping him

**Comment by johndotpub** [comment]
@MatthewHerbst / @sds I do! 😁 @sds I'll give you a shout.

**Comment by lencioni** [comment]
@tdooner @twooster PTAL, thanks

**Pull request merged**
